import logging


LOG_LEVEL = logging.DEBUG

WIN_WIDTH = 800
WIN_HEIGHT = 640

CAPTION = "Mapper"
WINDOW_SIZE = WIN_WIDTH, WIN_HEIGHT
BACKGROUND_COLOR = 30, 150, 50
# BACKGROUND_COLOR = "#0099FF"
DELAY = 16


# PLAYER_POS = (WIN_WIDTH / 2, WIN_HEIGHT / 2)
# MAP_POS = (0, 0)
# GRID_SIZE = 32
